# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-26 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlateSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=100)),
                ('well', models.CharField(max_length=100)),
                ('barcode_id', models.CharField(max_length=100)),
                ('scan_id', models.CharField(max_length=100)),
                ('sample_name', models.CharField(max_length=100)),
                ('dilution_for_agilent', models.FloatField(null=True)),
                ('dil_conc', models.FloatField(null=True)),
                ('rna_rin', models.FloatField(null=True)),
                ('ribo_28S_16S', models.FloatField(null=True)),
                ('agilent_ng_per_ul', models.FloatField(null=True)),
                ('agilent_corr_ng_per_ul', models.FloatField(null=True)),
                ('conc_to_use', models.FloatField(null=True)),
                ('ul_for_desired_amount', models.FloatField(null=True)),
                ('water_to_49_ul', models.FloatField(null=True)),
                ('ercc', models.IntegerField(null=True)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('project_driver', models.CharField(max_length=100)),
                ('driver_email', models.TextField(null=True)),
                ('request_id', models.CharField(max_length=100)),
                ('expected_completion_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PullInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=100)),
                ('pull_date', models.CharField(max_length=100)),
                ('assigned_tech', models.CharField(max_length=100)),
                ('barcode_id', models.CharField(max_length=100)),
                ('sample_name', models.CharField(max_length=100)),
                ('location_jane', models.CharField(max_length=100)),
                ('box_name', models.CharField(max_length=100, null=True)),
                ('shelf_jane', models.CharField(max_length=100)),
                ('rack_jane', models.CharField(max_length=100)),
                ('slot_jane', models.CharField(max_length=100)),
                ('grid_jane', models.CharField(max_length=100)),
                ('amount_jane', models.CharField(max_length=100)),
                ('vol_jane', models.CharField(max_length=100)),
                ('comments_from_request', models.TextField(null=True)),
                ('scan_id', models.CharField(max_length=100)),
                ('location_from_pull', models.CharField(max_length=100)),
                ('box_name_from_pull', models.CharField(max_length=100)),
                ('shelf_from_pull', models.CharField(max_length=100)),
                ('rack_from_pull', models.CharField(max_length=100)),
                ('slot_from_pull', models.CharField(max_length=100)),
                ('grid_from_pull', models.CharField(max_length=100)),
                ('amount_from_pull', models.CharField(max_length=100)),
                ('vol_from_pull', models.CharField(max_length=100)),
                ('comments_for_pull', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RequestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=100)),
                ('quote_number', models.CharField(max_length=100)),
                ('number_samples', models.CharField(max_length=100)),
                ('number_read', models.CharField(max_length=100)),
                ('amount_required', models.CharField(max_length=100)),
                ('volume_required', models.CharField(max_length=100)),
                ('request_date', models.CharField(max_length=100)),
                ('expected_completion_date', models.CharField(max_length=100)),
                ('protocol_type', models.CharField(max_length=100)),
                ('request_archivist', models.CharField(max_length=100)),
                ('requested_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SampleManifest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100)),
                ('sample_name', models.CharField(max_length=100)),
                ('sample_replicate', models.IntegerField()),
                ('sample_species', models.CharField(max_length=100)),
                ('sample_type', models.CharField(max_length=100)),
                ('sample_conc', models.FloatField(null=True)),
                ('sample_amount', models.FloatField(null=True)),
                ('project_id', models.CharField(max_length=100)),
                ('other', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TempPullRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=100)),
                ('scan_id', models.CharField(max_length=100)),
                ('sample_name', models.CharField(max_length=100)),
                ('location_jane', models.CharField(max_length=100, null=True)),
                ('box_name', models.CharField(max_length=100, null=True)),
                ('shelf_jane', models.CharField(max_length=100, null=True)),
                ('rack_jane', models.CharField(max_length=100, null=True)),
                ('slot_jane', models.CharField(max_length=100, null=True)),
                ('grid', models.CharField(max_length=100, null=True)),
                ('amount_jane', models.CharField(max_length=100, null=True)),
                ('vol_jane', models.CharField(max_length=100, null=True)),
                ('comments_from_request', models.TextField(null=True)),
            ],
        ),
    ]
