# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('talkLims', '0002_auto_20160826_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='platesetup',
            name='agilent_location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='platesetup',
            name='amount_from_plate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='platesetup',
            name='est_dilution',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='platesetup',
            name='plate_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='platesetup',
            name='plate_made_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='platesetup',
            name='plate_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='platesetup',
            name='sample_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='platesetup',
            name='vol_from_plate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='platesetup',
            name='barcode_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='platesetup',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='platesetup',
            name='ercc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='platesetup',
            name='request_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='platesetup',
            name='sample_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='platesetup',
            name='scan_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='platesetup',
            name='well',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
